# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-03 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='address',
        ),
        migrations.RemoveField(
            model_name='company',
            name='description',
        ),
        migrations.RemoveField(
            model_name='company',
            name='name',
        ),
        migrations.AddField(
            model_name='company',
            name='Designation',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='Location',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='Name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='Position',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
